### Consulta todas las tareas
GET http://localhost:3000/todos



### Consulta una tarea por su id
GET http://localhost:3000/todos/ca5fbf5f-c5d9-48d1-a45c-8be980e7b5aa

### Crear una tarea

POST http://localhost:3000/todos
Content-Type: application/json

{
    "title": "Testing de la API",
    "description": "Tarea para realizar con user",
    "completed": false
}

### Actualizar una tarea
PATCH http://localhost:3000/todos/0d467334-828a-41af-82ac-7ad7392ae7c4
Content-Type: application/json

{ 

  "title": "Django",
  "description": "Espero que funcione esto de Django",
  "completed": true,
  "userId": 1
}

### Eliminar una tarea
DELETE http://localhost:3000/todos/f5f82a18-8389-434d-b999-ca1c530b644e


###Consulta todos los usuarios
GET http://localhost:3000/api/users

### Consulta un usuario por su id
GET http://localhost:3000/api/users/1

### Consulta un usuario que no existe
GET http://localhost:3000/api/users/xit3r

### Crear un usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Camellonado",
    "email": "camellonaldo@gmail.com",
    "password": "12345678"
}

### Actualizar un usuario
PATCH http://localhost:3000/api/users/10
Content-Type: application/json

{
    "name": "Yehudi Sanabria",
    "email": "yehudi.sanabria16@gmail.com",
    "password": "AwqRtlcm4"
}

### Eliminar un usuario
DELETE http://localhost:3000/api/users/5

### Eliminar un usuario que no existe
DELETE http://localhost:3000/api/users/xit3r